// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IDPServer.Models;

public partial class CompanyCustomer
{
    public long Id { get; set; }

    public long? UserId { get; set; }

    public int? CompanyId { get; set; }

    public int? ShopCategoryId { get; set; }

    public int? ShopActivityId { get; set; }

    public int? GradeId { get; set; }

    public int? SalesBranchId { get; set; }

    public string CustomerCode { get; set; }

    public int? CollectionType { get; set; }

    public int? CollectionPeriod { get; set; }

    /// <summary>
    /// 1-sabt avalieh 2-taeedshodeh 3-taeednashodeh
    /// </summary>
    public int? Status { get; set; }

    public DateTime? ConfirmDate { get; set; }

    public int? UserConfirmId { get; set; }

    public string CreatedByUserId { get; set; }

    public DateTime? CreatedDateTime { get; set; }

    public string ModifiedByUserId { get; set; }

    public DateTime? ModifiedDateTime { get; set; }

    public Guid BusinessId { get; set; }
}